name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Trunk and Rust Target
      run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.11.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        rustup target add wasm32-unknown-unknown
    - name: Setup wasm-bingden-cli
      uses: jetli/wasm-bindgen-action@v0.1.0
    - name: Build
      run: ./trunk build --release --public-url my-index
    - name: Publish Github Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: dingkewz.com
