name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.11.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        cargo install wasm-bindgen-cli
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: ./trunk build --release
    - name: Publish Github Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_dir: dist
